Minor quality of life suggestions
surrealdb/surrealdb.net pull request #55
Opened 2023-11-27 22:55 UTC by simon-curtis

I have: 

- Added a RawValue property to the Ok result, in case someone wanted to cache the result or do custom deserialisation.
- Added an options builder delegate extension method `.AddSurrealDb(o => o.WithDatabase(...))`, it's the type I personally reach for the most when configuring services.

2023-11-28 17:53 UTC, Odonno requested changes
Looks nice. Some minor changes requested.

2023-11-28 18:15 UTC, simon-curtis commented
Regards the RawValue and Deserialising... it might make sense for us to just expose the JsonElement with a private setter?

2023-11-28 18:18 UTC, simon-curtis commented on SurrealDb.Net/Models/Response/SurrealDbResult.Ok.cs
> +
We already have an internal `IEnumerable<T> DeserializeEnumerable<T>()` signature

2023-11-28 18:35 UTC, simon-curtis commented on SurrealDb.Net/Models/Response/SurrealDbResult.Ok.cs
> +
We already had `internal IEnumerable<T> DeserializeEnumerable<T>()` but I have made a new public method with the `GetValues` name to keep it inline with GetValue

2023-11-28 18:36 UTC, simon-curtis commented on SurrealDb.Net/Models/Response/SurrealDbResult.Ok.cs
> +    public string RawValue => _value.GetRawText();
See my comment reg. exposing _value as a get-only property instead

2023-11-28 18:36 UTC, simon-curtis commented on SurrealDb.Net/Models/Response/SurrealDbResult.Ok.cs
> +    public string RawValue => _value.GetRawText();
See my comment reg. exposing _value as a get-only property instead

2023-11-28 18:44 UTC, simon-curtis commented
I've made the changes requested. Also I have added a check in the `SurrealDbOkResult.DeserializeEnumerable<T>()` to ensure that the result of the query was an array. I was going to just yield the object and then return early but if someone is calling `DeserializeEnumerable` (or `GetValues`) then I would assume the behaivour they were after was an array. I.e. if they have queried `SELECT * FROM ONLY person` I would not expect them to call an array method.

2023-11-28 19:13 UTC, Odonno approved these changes
[![image](https://github.com/surrealdb/surrealdb.net/assets/6053067/94941c82-9f02-48ef-8326-bbefe0984924)](https://media.tenor.com/JMr_dlDTHJIAAAAC/theboys-perfect.gif)

2023-11-30 10:06 UTC, kearfy commented
Hey @simon-curtis, formatting seems to fail. Could you check that out? Thanks!

2023-11-30 10:40 UTC, Odonno commented
Indeed, this project is using https://csharpier.com/

You can run it locally in the cli by installing the dotnet tool on your machine. Or automatically in your favorite IDE as an extension. There is one for Rider.

I will update the readme for newcomers.

2023-11-30 10:45 UTC, simon-curtis commented
I've formatted but it hasn't made any changes?

2023-11-30 11:18 UTC, simon-curtis commented
All done! Codespaces had checkout the wrong branch for some reason. Yes the space after the the property is gone now

2023-11-30 14:08 UTC, merged